# Utiliza una imagen base de Python
FROM python:3.11.4

# Copia el archivo requirements.txt al contenedor
COPY requirements.txt .

# Instala las dependencias de la aplicación
RUN pip install -r requirements.txt

# Copia todo el contenido del directorio actual al contenedor
COPY . .

# Expone el puerto 8080 para Gunicorn
EXPOSE 8080

# Comando para iniciar la aplicación con Gunicorn
CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:8080", "app:app"]
